// Generated by workers/clipper/scripts/render_previews.py -- do not edit by hand.
// Template value -> preview loop in apps/web/public/templates/.
export const TEMPLATE_VIDEOS: Record<string, string> = {};
