#!/usr/bin/env python
"""
Render the template preview loops shown in the web app's style picker.

    python scripts/render_previews.py path/to/sample.mp4 [--start 2 --seconds 7]

Use a short clip of a real person talking to camera (20-60 s) that Zepply has
the rights to show publicly -- these loops appear on every user's Create page.

What it does:
1. Runs the full pipeline once on the sample with one clip (transcription,
   moment-finding, and the post kit -- this spends API credit once).
2. Restyles that clip in every edit template, from the run's analysis bundle.
3. Cuts a loop from each render, compresses it, and writes
   apps/web/public/templates/<template>.mp4 plus
   apps/web/components/create/clips/template-videos.ts, which the picker reads.

Story-visual templates (editorial, explainer, signal) need Claude credit; without
it their loops show the captions only, and the script says so.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT.parents[1] / "apps" / "web"
PUBLIC = WEB / "public" / "templates"
MANIFEST = WEB / "components" / "create" / "clips" / "template-videos.ts"

# Mirrors apps/web/lib/clip-templates.ts: what each template switches on.
TEMPLATES: dict[str, list[str]] = {
    "kinetic": ["--style", "kinetic"],
    "comment": ["--style", "karaoke", "--card", "--cta-keyword", "LINK"],
    "editorial": ["--style", "emphasis", "--broll", "--look", "editorial"],
    "explainer": ["--style", "pill", "--broll", "--look", "explainer", "--no-effects"],
    "signal": ["--style", "caps", "--broll", "--look", "signal", "--no-effects"],
    "simple": ["--style", "clean"],
}


def clipper(*args: str) -> None:
    cmd = [sys.executable, "-m", "clipper.cli", *args]
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=ROOT, check=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("sample", help="a short talking-head clip Zepply may show publicly")
    ap.add_argument("--out", default=str(ROOT / "out" / "previews"), help="working folder")
    ap.add_argument("--start", type=float, default=2.0, help="loop start within the rendered clip (s)")
    ap.add_argument("--seconds", type=float, default=7.0, help="loop length (s)")
    ap.add_argument("--accent", default="#3888F0", help="accent colour for the previews")
    ap.add_argument("--only", nargs="*", help="render just these templates")
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    sample = str(Path(args.sample).resolve())

    # 1. One full run, one clip: the analysis every template reuses.
    if not (out / "base" / "work" / "ranked.json").exists():
        clipper("--out", str(out), "run", sample, "--name", "base", "--top", "1", "--render-workers", "1")
    from clipper import bundle
    from clipper.config import paths_for

    archive = bundle.make(paths_for("base", out), out / "base.tar.gz")

    # 2. Every template, from that bundle.
    PUBLIC.mkdir(parents=True, exist_ok=True)
    made: dict[str, str] = {}
    for name, flags in TEMPLATES.items():
        if args.only and name not in args.only:
            continue
        shutil.rmtree(out / name, ignore_errors=True)
        clipper("--out", str(out), "restyle", sample, "--bundle", str(archive), "--rank", "1",
                "--name", name, "--render-workers", "1", "--accent", args.accent, *flags)
        clip = out / name / "clip_01.mp4"
        broll = out / name / "clip_01_broll.json"
        if "--broll" in flags and not (broll.exists() and json.loads(broll.read_text())["moments"]):
            print(f"! {name}: no story visuals were made (no Claude credit?); the loop shows captions only")
        # 3. A short, small loop for the web.
        dest = PUBLIC / f"{name}.mp4"
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", str(args.start), "-t", str(args.seconds),
                        "-i", str(clip), "-an", "-vf", "scale=540:-2,fps=30", "-c:v", "libx264",
                        "-preset", "slow", "-crf", "27", "-pix_fmt", "yuv420p", "-movflags", "+faststart",
                        str(dest)], check=True)
        made[name] = f"/templates/{name}.mp4"
        print(f"  {dest} ({dest.stat().st_size // 1024} KB)")

    # The picker's map of template -> video, merged with any made earlier.
    existing = {p.stem: f"/templates/{p.name}" for p in PUBLIC.glob("*.mp4")}
    existing.update(made)
    body = ",\n".join(f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in sorted(existing.items()))
    MANIFEST.write_text(
        "// Generated by workers/clipper/scripts/render_previews.py -- do not edit by hand.\n"
        "// Template value -> preview loop in apps/web/public/templates/.\n"
        f"export const TEMPLATE_VIDEOS: Record<string, string> = {{\n{body}{',' if body else ''}\n}};\n",
        encoding="utf-8")
    print(f"wrote {MANIFEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
